### ISSUE TITLE
hanging laragon process

### ISSUE THREAD

**Issue by cubakcabak** [leokhoa/laragon#102]
os: win10 1903

using latest laragon portable, nginx-16 stable, php-7.3.7-nts, mariadb-10.4.6

when i try to "stop all", laragon hanging and windows ask if i would like to force close it

observing the process in taskmanager, seems that SendSignalCtrlC.exe failed to stop the php and nginx process

mysql stopped fine

**Comment by leokhoa** [comment]
@cubakcabak : SendSignalCtrlC.exe will try to graceful shutdown your processes.
Does the issue happen often?

**Comment by cubakcabak** [comment]
each and everytime

wether i try to "reload" or "stop all", always hanging

**Comment by leokhoa** [comment]
@cubakcabak : Strange. Are you using any AV?

**Comment by cubakcabak** [comment]
yes, mcafee vse

and yes, i have tried disable the AV, but the results are the same

**Comment by manishlok** [comment]
same issue here, when i try to reload or refresh, it hangs.

**Comment by cubakcabak** [comment]
the problem doesn't occur with latest main and stable nginx anymore
