### ISSUE TITLE
Apache 2.4.39 and Fcgid module 2.3.10 VS16 Windows Binaries

### ISSUE THREAD

**Issue by w3suli** [leokhoa/laragon#108]
[https://www.apachelounge.com/download/](https://www.apachelounge.com/download/)

It would be a good idea to update the modules in the etc directory (php nts).

A warning appears when you select php ts. In my experience, php VC15 works fine as an apache VS16 module as well.
![laragon](https://user-images.githubusercontent.com/20889555/62411175-9b5ec000-b5ef-11e9-88c3-09ca9359fc2a.png)

**Comment by leokhoa** [comment]
@w3suli : Can you change the name of Apache to: httpd-2.4.39-win64-VC15-hack?

**Comment by w3suli** [comment]
Yes.
For example: httpd-2.4.39-win64-VC15-VS16
This is also a good way to avoid being warned.

Thanks.

**Comment by leokhoa** [comment]
@w3suli : Many thanks for your information.
I've built a new version of Laragon 4.0.16 to fix it:
https://github.com/leokhoa/laragon/blob/dev/laragon.exe

**Comment by w3suli** [comment]
Working perfectly!
