### ISSUE TITLE
ready for vscode?

### ISSUE THREAD

**Issue by charliezzo** [leokhoa/laragon#129]
Please use visual studio code or sublime text instead of notepad++, they are more powerful, thanks

**Comment by leokhoa** [comment]
@charliezzo : Thanks. Laragon is pluggable, user can add VS Code with 1-Click:
**Menu > Tools > Quick add > Code**
Laragon will add the latest version of Code to its core system.

**Comment by charliezzo** [comment]
Thanks
laragon is very good

**Comment by charliezzo** [comment]
I want terminal & VSCode in my desktop mouse-right-click menu .but notepad++
How can i setting

**Comment by leokhoa** [comment]
@charliezzo : Sure, you can. Please follow my instruction here:
https://forum.laragon.org/topic/1731/add-notepad-and-terminal-to-the-right-click-menu/3

**Comment by charliezzo** [comment]
Very thank u

**Comment by abrhambas01** [comment]
Hey, I want to ask if how do u connect git with cmder to VSCode ? Adding this in `settings.json`?
` "git.path": "F:\\laragon_2\\bin\\git\\bin\\git.exe"`
