### ISSUE TITLE
TDE Encryption

### ISSUE THREAD

**Issue by KennethVDS** [leokhoa/laragon#132]
I am working withMySQL 5.7 and want to generate a keyring.dll for encrypting at rest with the built in TDE function.
Does anyone have a great step by step tutorial? 
The point i am stuck in right now is giving permission for sql to modify my keyring file. 
I can't seem to find the right object name. Pls help before my boss kills me.

**Comment by leokhoa** [comment]
@KennethVDS : This video MySQL 8 but you will find some useful information:
https://www.youtube.com/watch?v=JpZQTH5DmBE
