### ISSUE TITLE
WordPress sites wp-config not setup

### ISSUE THREAD

**Issue by mnelson4** [leokhoa/laragon#14]
When I create a new WordPress site, its really awesome fast.
I see it adds all the files, the db, and whatever webserver magic I need. You just need to configure the wp-config.php file yourself.
I think that could be done automatically, no? And it would probably be easier on the user.
On first try, I didn't know what the automatically created database was called, what user to use, or what password to use. (I soon learned, looking at the auto-created db, and the fact that clicking "db" from within Laragon auto-populated my HeidiSQL window with some settings, that it's the same name as the project (as a slug, so all lower case and with dashes, the user is "root" and the password is a blank string).
It would just be a matter of creating the wp-config.php file, and adding values for the database name, user and password.
On this topic, if the Laragon code were actually open source, I could contribute to this feature...

**Comment by mnelson4** [comment]
woah, I see @leokhoa just added all the code to this repo. awesome! Now to follow through on what I was saying...

**Comment by leokhoa** [comment]
@mnelson4 : That's a good idea. I will implement it right away. 
Btw, Laragon is developed using Delphi - a nice tool but is very expensive (https://www.embarcadero.com/products/delphi)
I still use a very old version of Delphi (2009) and I don't think you need to use it :)

Anyway, thanks for your suggestion.

**Comment by mnelson4** [comment]
woah, yes I see. Ya that does have a good price tag, and at that rate I can understand how you might be using an old version.
And thanks!

**Comment by mnelson4** [comment]
awesome. I just downloaded 3.3.2 and gave it a whirl: when WordPress asks you to setup the database connection, it's already setup with the correct database name, username and password. Great!
I could see some users still wondering if they need to change any of those settings though (eg, someone might not realize that those defaults are what's correct for that site, they might wonder if they need to change them, which previously they did.)
I hope you don't mind if I offer a suggestion on a different way to implement: right now, I see you're editing the WordPress core file `wp-admin/setup-config.php`, which works well enough. (So this is the current UX: https://drive.google.com/file/d/140RXjk7K3M0NrqVWfrFK3iNOF-PaifR1/view)
But it would skip a step if you instead just copied `/wp-config-sample.php` into `/wp-config.php`, and replaced `database_name_here`, `username_here,` and `password_here`. Then folks setting up a database wouldn't even need to do any of the `setup-config.php` steps 0-2. Eg the UX would be this: https://drive.google.com/file/d/1lyPDGjboME_FChwi4nnCL5sJtt_-zQrf/view (minus the parts where I manually copied `wp-config-sample.php` to `wp-config.php` and set the setting in it, I'm hoping the installer could take care of that). 
That approach would be a simpler UX, avoid hacking WP core files, and users don't have to even wonder if they need to change database settings (they're never even bothered with them).

**Comment by leokhoa** [comment]
I wanted the users to be familiar with installing setup so I did it that way (developer view).
However, after reviewing your suggestion, I am so convinced that it's a good idea.
I've released Laragon 3.3.3 with your solution.

You rock!

**Comment by mnelson4** [comment]
Yeah, I can see some motivation for the way you did it. For example, folks can set a different database prefix if they want.
But I think if folks want that for some reason, they're probably comfortable opening up wp-config.php themselves and editing it directly.
Still, I personally would prefer skipping the `wp-admin/setup-config.php` steps, and just have `wp-config.php` created automatically. That's what all the hosting companies' one-click installers do.
Sounds great, thanks!
All the hosting companies' one-click installs

**Comment by mnelson4** [comment]
I just downloaded Laragon 3.3.3 from sourceforge and gave this a whirl. It works exactly how I hoped it would. Beauty!
