### ISSUE TITLE
Stop advertising as if it was cross-platform program?

### ISSUE THREAD

**Issue by imakin** [leokhoa/laragon#143]
On the website Linux is mentioned many times, 

https://laragon.org/testimonials/

but to this day, laragon still does not provide linux version. Those testimonials should be omitted as they are miss leading. People will thought this is cross-platform application, only to get upset moments later when they can't find the package for Linux or Mac OS.

In reality most programmer (especially web developer) use Linux and Mac OS because they are **easier** for programming (not because being hardcore fans).
anyway, thanks for creating laragon.

**Comment by leokhoa** [comment]
@imakin : Let me clarify you. On the testimonial site, there are 2 places mentioned Linux:
1. _yup I love laragon, I'm forced now to work on **Linux** and can't find anything similar..._
-> He mentioned that in the past, he worked on Windows then he was forced to work on Linux and he could not find a program in Linux similar to Laragon on Windows

2. _I've been using Valet for **Linux**, LAMPP, Docker, Vagrant, etc..but IMHO those haven't been able to give as pleasant experience as hoped for while developing web apps like Laragon._
Truly isolated environment with easily swappable PHP/MySQL/etc version...
-> He mentioned that he has used many tools in Linux, but they haven't been able to give as pleasant experience as Laragon.

I did not advertise it cross-platform. Even it easy to me to make it cross-platform.
