### ISSUE TITLE
Run script on close

### ISSUE THREAD

**Issue by thanosalexander** [leokhoa/laragon#145]
Hi.. however Procfile is very helpful and usefull, i think it'd be almost the same important the need for a script to run after stop all laragon..
e.g we maybe start a service like elasticsearch on start and we'll need to close it when we stop all
Maybe you can check on stop all, if there is a file after.bat and if exist just execute it

**Comment by leokhoa** [comment]
@thanosalexander : I will consider to add that.

**Comment by thanosalexander** [comment]
Thanks!
