### ISSUE TITLE
Windows terminal instead of conemu

### ISSUE THREAD

**Issue by Davidnadejdin** [leokhoa/laragon#146]
How about using [this](https://github.com/microsoft/terminal) instead conemu?

**Comment by leokhoa** [comment]
@Davidnadejdin : Do you use it?

**Comment by Davidnadejdin** [comment]
> @Davidnadejdin : Do you use it?

yes

**Comment by nuno-andre** [comment]
You have to add `WindowsTerminal.exe` to `laragon.ini`:

```
[ui]
Terminal=WindowsTerminal: "wt.exe -d ."
```

But [Windows Terminal's arguments](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) parsing is not enough consistent yet, so if you want to run some elaborate command I recommend you to call it from a PowerShell script. For example:
```
[ui]
Terminal=WindowsTerminal: "powershell.exe ./terminal.ps1"
```

```
# terminal.ps1 in Laragon's folder
wt.exe `
new-tab -d www -p cmd `; `
split-pane -d . -H -p Windows` PowerShell `; `
split-pane -d 'bin/nginx' -p cmd cmd /k "${env:LARAGON_ROOT}laragon.exe reload nginx"
```

Note that all those grave accents are needed to parse the command correctly.
