### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [leokhoa/laragon#147]
There is no LICENSE or COPYING file for this project. The default is copyright.

You should license this project under the AGPL3 or GPL3 license. Directions on how to apply the license are at the bottom of the license file under the `How to Apply These Terms to Your New Programs` heading.  There is a helpful guide for the GPL at https://www.gnu.org/licenses/gpl-howto.en.html.  If you would like me to submit a PR to make this easier, I would be happy to do that.

**Comment by leokhoa** [comment]
@TechnologyClassroom : Yes, please.
Many thanks!

**Comment by TechnologyClassroom** [comment]
AGPLv3 or GPLv3?

**Comment by QWp6t** [comment]
...but it's not even open source so what exactly are you trying to license? the config files? 🤣

**Comment by leokhoa** [comment]
Laragon is written in Delphi 2009 - a commercial IDE. Open sourcing it has no value but brings security risks and burden to me.

**Comment by TechnologyClassroom** [comment]
[Security through obscurity is a poor stance to take on security.](https://en.wikipedia.org/wiki/Kerckhoffs's_principle)
