### ISSUE TITLE
Suddenly Laragon is not working. What to do?

### ISSUE THREAD

**Issue by anburocky3** [leokhoa/laragon#150]
Web Server, MySQL, Terminal. (Everything is not working.)

Service MySQL can not start. Reason: 'S:\laragon\bin\mysql\mysql-5.7.24-winx64\bin\mysqld' is not recognized as an internal or external command, operable program or batch file.

**Comment by leokhoa** [comment]
@anburocky3 : Is your OS 32-bit?

**Comment by anburocky3** [comment]
Its Windows 10 64bit. I think it has something to do with antivirus. Run entire scan. Now its working as expected. :) Thanks for commenting.

**Comment by tyfricko** [comment]
If anybody has the same problem I solved it by rewriting with a fresh copy of the database files in the "x:\laragon\bin\mysql\" folder.
