### ISSUE TITLE
[Feature] Presets

### ISSUE THREAD

**Issue by JABirchallHR** [leokhoa/laragon#155]
First of all, I love larago, its a great tool for developement eviroment, Great work!

I work on a plathera of diffrent projects with diffrent setups, from PHP, node and oth at the same with switching between nginx and acpahe. I would like to suggest presets to be added to laragon, How it could work (open for discussion). You create a setup like you do now with what services, extentions and configurations you want enabled. When you press `presets->new preset` in the menu it will create a folder in the laragon directory `laragon/presets/{preset name}` and copy your current enviroment into it. 
All folders in the `laragon/presets` folder will show under the presets menu item. 

Presets can have options under them like Switch presets, rename, delete, open directory and clone.

Discuss?

**Comment by leokhoa** [comment]
@JABirchallHR : Most of the time you can only work on a project, so I suggest you to take advantage of the portability of Laragon to create multiple instances of Laragon:
For example:
- C:\laragon-apache-php7.4
- C:\laragon-nginx-php7.3-node11
