### ISSUE TITLE
Laragon 4.0.16 NO NGROK OPTION (screenshot)

### ISSUE THREAD

**Issue by samjco** [leokhoa/laragon#164]
![image](https://user-images.githubusercontent.com/3359062/79530249-6b980100-8034-11ea-8690-c598e4b01c46.png)

_Originally posted by @samjco in https://github.com/leokhoa/laragon/issues/163#issuecomment-615024466_

**Comment by leokhoa** [comment]
@samjco : **Menu > Local Sites > Share**
Please don't use Space in your path otherwise you will face headache later.

**Comment by samjco** [comment]
Where do you see Space?

**Comment by leokhoa** [comment]
" Local Sites"

**Comment by samjco** [comment]
OH wait!!

So when a user defines a custom FOLDER path, Laragon changes the name from "www" to whatever the path name is??

**Comment by leokhoa** [comment]
That's right!
