### ISSUE TITLE
how do i enable the redis extension to be loaded ? 

### ISSUE THREAD

**Issue by abrhambas01** [leokhoa/laragon#170]
I tried downloading from this link
```
https://pecl.php.net/package/redis/4.1.0/windows
```

and put it inside here

Laragon -> F:\laragon_2\bin\php\php-7.2.19-Win32-VC15-x64

- My current redis version is***
```
$ redis-server --version
Redis server v=3.2.100 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=dd26f1f93c5130ee
```

I edited the `php.ini` file by adding this already
```
extension=php_redis.dll
```
but my redis extension is not loaded when I run `extension_loaded("redis"): it still is false

**Comment by leokhoa** [comment]
@abrhambas01 : This link will help:
https://itanea.fr/apprendre-le-developpement-web/installer-une-version-plus-recente-de-redis-sur-laragon/

**Comment by abrhambas01** [comment]
thanks nevermind got it already
