### ISSUE TITLE
Redis 5.x.x

### ISSUE THREAD

**Issue by robsonpiere** [leokhoa/laragon#174]
Native port of Redis for Windows, currently in version 5.

Author: @tporadowski 
[https://github.com/tporadowski/redis/releases](https://github.com/tporadowski/redis/releases)

**Comment by leokhoa** [comment]
Thanks @robsonpiere

**Comment by tporadowski** [comment]
From what I've seen you are bundling Redis for Windows in your application, so please let me know if you need any specific changes to the MSI installer or binary distribution in ZIP archive (just open an issue and I will have a look if it could be included). They are mostly the same though as they were distributed by the MS OpenTech team at the time they maintained it.

**Comment by leokhoa** [comment]
Thanks @tporadowski. What you have done is amazing! 
When MS (with a lot of resources) stopped supporting Redis, I thought no one will port it to higher version. 
Laragon is portable so upgrading Redis is very easy.
1. Download the latest release: https://github.com/tporadowski/redis/releases/download/v5.0.9/Redis-x64-5.0.9.zip 
and extract it to:
**C:\laragon\bin\redis**

2. Update laragon.ini (**Menu > Laragon > laragon.ini**), change:
```
[redis]
Version=Redis-x64-5.0.9
Use=-1
```
3. Exit Laragon and start again, users should have Redis 5.0.9
![image](https://user-images.githubusercontent.com/9049575/82187122-22c6b700-9916-11ea-9edf-b30dad5d53af.png)


I will make a tutorial on this soon. This will help to promote your awesome work.

**Comment by robsonpiere** [comment]
I was successful using redis 5. Congratulations on the great work! 
@tporadowski  @leokhoa 

👏👏👏👏👏

**Comment by kubila** [comment]
I solved my issue via @leokhoa solution, thanks for your effort, using redis 5.0.10.
And thanks to you @tporadowski for laragon.

**Comment by disturbed-pixel** [comment]
thanks guys this worked perfectly!

looking forward to testing out redis 7 in laragon

**Comment by robsonpiere** [comment]
I'm closing this issue because the redis was updated in Laragon version 6.0.0
Thanks!
