### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by ElGigi** [leokhoa/laragon#187]
Hi,

I test PHP 8 with Laragon.

But **php*X*_module.dll** has been renamed with PHP 8, it's now: **php_module.dll** (with version number)
So i need to edit file manually : `...\etc\apache2\mod_php.conf`
And changes: `LoadModule php8_module "..."` with `LoadModule php_module "..."`

Link to download PHP 8 for Windows: https://windows.php.net/downloads/snaps/master/rfc76509/

Regards.

**Comment by leokhoa** [comment]
@ElGigi : Thanks for your head up. I am aware of it and will make a hotfix soon:
https://forum.laragon.org/topic/2092/php-8-0-8-0-0alpha1-testing-anyone

**Comment by ElGigi** [comment]
Any news?

**Comment by leokhoa** [comment]
@ElGigi: I am going to publish a big release of Laragon - Laragon 5
So stay tune...

**Comment by ElGigi** [comment]
Perfect, thanks 👍

**Comment by gavinr** [comment]
@leokhoa thanks - looking forward to this!

**Comment by aldemeery** [comment]
+1 Looking forward to it too...

**Comment by bnbabu55** [comment]
awesome news man, looking forward to this also.

**Comment by tsakowi** [comment]
89 / 5000
@leokhoa Laravel 5 news? PHP 8 is here and I am eager to test it in Laravel 5.
Thank you

**Comment by deulizealand** [comment]
> @ElGigi: I am going to publish a big release of Laragon - Laragon 5
> So stay tune...

make it for linux too

**Comment by aurawindsurfing** [comment]
> @ElGigi: I am going to publish a big release of Laragon - Laragon 5
> So stay tune...

Hey @leokhoa any news in relation to the 5.0 release? Thanks!

**Comment by mathmul** [comment]
While we're all eager for the new version, I'll say let's leave the guy to polish it out, as he seems fit.

Until the project becomes open source, we can only be grateful that the best local development tool project has not yet been abandoned.

The php8_module -> php_module is just one of the issues than needs to be resolved. Another with PHP8 is that reloading Apache after version change to PHP7 and back to PHP8 (with repairing php_module) yields 403 forbidden. Same as reloading Apache after changing php.ini for PHP8.

There's a simple [workaround](https://stackoverflow.com/questions/65688320/why-does-changing-php-ini-and-reloading-apache-in-laragon-result-in-403-forbidde) but let's wait patiently for the version that gets rid of major issues.

**Comment by leokhoa** [comment]
Thanks @mathmul.
@aurawindsurfing : I can't make any promise on the release date but some date in this March is on my plan.

**Comment by indigoram89** [comment]
+1

**Comment by t0sk-fak3r** [comment]
+1

**Comment by forxer** [comment]
@leokhoa now that you have released 5.0, could you look at the problem with php8? 

Because the operations when you switch PHP7 / PHP8 regularly in a day are a bit painful to do each time

Thanks

**Comment by leokhoa** [comment]
@forxer , @ElGigi : The issue is fixed in Laragon 5.0

**Comment by ElGigi** [comment]
Thanks.

**Comment by forxer** [comment]
oh my bad, I have actually updated to version 5 and everything is working fine

thank you so much @leokhoa
