### ISSUE TITLE
MySQL 5.1 error

### ISSUE THREAD

**Issue by LazyGeniusMan** [leokhoa/laragon#190]
I tried to install another MySQL version, the version I want to install is 5.1.73, but when I start laragon this error show up

![image](https://user-images.githubusercontent.com/58850480/89274796-9baef280-d66b-11ea-8123-43366b98ad93.png)

I downloaded MySQL from [this](https://downloads.mysql.com/archives/get/p/23/file/mysql-noinstall-5.1.73-winx64.zip) and place it in C:\laragon\bin\mysql , and then delete C:\laragon\data

Anything wrong with my step? when I switch back MySQL version to default version it's running fine.

**Comment by leokhoa** [comment]
@LazyGeniusMan : MySQL 5.1 is too old.
The Laragon portable comes with MySQL 5.1, you can use it.

**Comment by LazyGeniusMan** [comment]
> 
> 
> @LazyGeniusMan : MySQL 5.1 is too old.
> The Laragon portable comes with MySQL 5.1, you can use it.

Ah ok thanks, did not noticed that.
