### ISSUE TITLE
ERROR 1071 (42000) at line 1753: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by takielias** [leokhoa/laragon#194]
I tried to import DB from wamp according to [this](https://laragon.org/download/migrate-from-wamp.html) tutorial but Got 
**ERROR 1071 (42000) at line 1753: Specified key was too long; max key length is 1000 bytes** 
[ScreenShot](https://prnt.sc/tykdqu)
How can I fix it?

**Comment by leokhoa** [comment]
@takielias : Google is your friend:
https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes
