### ISSUE TITLE
Exception EAccessViolation in module laragon.exe at 0011B331

### ISSUE THREAD

**Issue by waptik** [leokhoa/laragon#20]
Hi, can i get some help?
On my machine, i have two users. One was an admin but the wasn't. 
Case 1: I installed laragon on using the non-admin account and it was working perfectly. But i uninstalled with the administration account. Later i moved back to the non-admin account and re-installed it back again and that's how this error window shows up.
Case 2: I uninstalled it again this time around using the non-admin account and re-installed it again using the admin account and it's running perfectly. But when i use laragon with the non-admin account this error shows back again.
Case 3: So i uninstalled it again from the admin account and started with Case 1 again i still face the same error.

My OS is Win 8.1
Here is the screenshot of the error

![laragon-error](https://user-images.githubusercontent.com/1687551/43641375-6dd20c5a-96f1-11e8-83bb-292b2c7f5e15.PNG)

**Comment by leokhoa** [comment]
@waptik : I have no idea why it happened. You can try Laragon 3.5 which is the latest version with some bug fixes.

**Comment by waptik** [comment]
Thanks. i will do that or rather use it only in master account(main account)

**Comment by andrelcb** [comment]
Did you find the error?

**Comment by waptik** [comment]
> Did you find the error?

Yes, it's because the user account didn't admin privileges on that machine(non-admin account). So i had to use it from an admin account. 
Fixed the issue.
