### ISSUE TITLE
Path must not have space!

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [leokhoa/laragon#205]
Running this program from my desktop where my username has a space "First Last" does not work. Is there a way to enclose the run params/urls in a string?

**Comment by leokhoa** [comment]
@zgjimgjonbalaj : There are many services that will not work well if having space in Path.
You shoud move Laragon to somewhere else.

**Comment by zgjimgjonbalaj** [comment]
> @zgjimgjonbalaj : There are many services that will not work well if having space in Path.
> You shoud move Laragon to somewhere else.

Thanks for your response and sounds good!

**Comment by Quest79** [comment]
> @zgjimgjonbalaj : There are many services that will not work well if having space in Path. You shoud move Laragon to somewhere else.

They are bad too. What an awful reason not to improve. Instead of moving folders I moved to better software.
