### ISSUE TITLE
Forum down?

### ISSUE THREAD

**Issue by KoolPal** [leokhoa/laragon#209]
Hi,

The forum https://forum.laragon.org/ seems down

Shows
504 Gateway Time-out
nginx/1.10.3 (Ubuntu)

Is this a planned downtime?

Please resolve

Thanks

**Comment by leokhoa** [comment]
Hi @KoolPal 
It is not planned downtime. The current VPS hosting arubacloud is not scalable. I will migrate to a new hosting service soon.
