### ISSUE TITLE
Unable to start postgres

### ISSUE THREAD

**Issue by rallisf1** [leokhoa/laragon#212]
Windows 10 x64 version 10.0.19041.630 in Greek Language

I get this error when trying to start postgresql
[![psql.jpg](https://i.postimg.cc/G3FbxBF6/psql.jpg)](https://postimg.cc/NL0hgjPx)

I tried both version 11 from Laragon installer and manually downloaded version 12 binaries, same error.

The windows user name is in Greek, I suspect that is the problem but the whole point of going portable is for things like this not to matter.

**Comment by leokhoa** [comment]
@rallisf1 : Yes, the Greek username is the culprit. Can you change your username for testing purpose?
I will find a way to fix that.

**Comment by rallisf1** [comment]
> @rallisf1 : Yes, the Greek username is the culprit. Can you change your username for testing purpose?
> I will find a way to fix that.

I did try to change it but nothing changed except the display name. Turns out you need to log off/restart for the username to change. It works now. $@#$@! MS

**Comment by leokhoa** [comment]
@rallisf1 : I'm glad to hear that :)

**Comment by pututdev** [comment]
nice information thanks you
