### ISSUE TITLE
Exception EReadError in module laragon.exe at 000284AE

### ISSUE THREAD

**Issue by lrdeoliveira** [leokhoa/laragon#231]
I formatted the computer, after reinstalling started this problem, the first time I have this problem

cannot able to start laragon giving error
Exception EReadError in module laragon.exe at 000284AE

**Comment by lrdeoliveira** [comment]
resolvido

**Comment by radovog** [comment]
Hello, how did you solve the problem?

**Comment by hventura** [comment]
> resolvido

Could you please share how did you resolve the issue?
