### ISSUE TITLE
error popup: too small/truncates text, error text not copiable

### ISSUE THREAD

**Issue by torvista** [leokhoa/laragon#233]
For example:
![Clipboard02](https://user-images.githubusercontent.com/4391026/111897907-f9d5ed80-8a22-11eb-96ca-4fc079ba93d9.gif)

Is is not possible to allow the popup to stretch to the text length?

Also, would it be possible to allow the text to be copied to aid searching for that error?

**Comment by leokhoa** [comment]
@torvista : 
1. The width is fixed by Windows
2. You can copy the text by pressing Ctrl+C

**Comment by torvista** [comment]
> You can copy the text by pressing Ctrl+C

Indeed you can!
