### ISSUE TITLE
auto.openssl.conf adding Document Root when Auto Virtual Hosts is off

### ISSUE THREAD

**Issue by Quirinus** [leokhoa/laragon#245]
Laragon Full 4.0.16 190914
Laragon\etc\ssl\auto.openssl.conf auto adds folders from the Document Root (using the Auto Virtual Hosts format), even though I have Auto Virtual Hosts turned off. I have added some to the usr\tpl.openssl.conf.tpl.

I'm not sure if it's a bug or intentional.

**Comment by leokhoa** [comment]
@Quirinus : It is intentional.
The Auto SSL helps you control SSL certs not only for Auto Virtual Hosts but also other hosts: localhost, your managed hosts.
