### ISSUE TITLE
Heroku CLI output invisible in Terminal (Cmder)

### ISSUE THREAD

**Issue by tertek** [leokhoa/laragon#246]
`λ heroku` returns output but is not visibile in Cmder. I am not sure if this is a problem with Cmder in general or with this packed version, so I wanted to share the issue and see if anyone can confirm/reproduce the problem.

I m on Windows 10 and Terminal / Windows Terminal are outputting heroku commands correctly.
Tried to switch themes which did not help.

**Comment by leokhoa** [comment]
It could be a problem with old version of Cmder. It works well with the latest version of Cmder.
Laragon 5 will allow you to update Cmder yourself. I will release it soon.

![image](https://user-images.githubusercontent.com/9049575/116725390-0a0ebe80-aa0c-11eb-81f1-b5cd49d77d5c.png)
