### ISSUE TITLE
Does not work with latest PHP release (7.2.9)

### ISSUE THREAD

**Issue by Swiftnesses** [leokhoa/laragon#25]
It seems something changes and now adding the latest windows build does not work. Clicking the extensions menu shows no extensions active (clicking one has no effect).

**Comment by Swiftnesses** [comment]
Seems it's because the extensions were named (example):

;extension=php_bz2.dll

and now it's:

;extension=bz2

**Comment by leokhoa** [comment]
@Swiftnesses : What is your Laragon version? I remember this kind of issue had been fixed long time ago.

**Comment by Swiftnesses** [comment]
3.4

**Comment by leokhoa** [comment]
Strange. I fixed it a year ago:
https://forum.laragon.org/topic/609/php-7-2-drop-down-menu-extension-enable-disable-does-not-work

Let me check and get back to you later.

**Comment by Swiftnesses** [comment]
Thanks!

**Comment by diomed** [comment]
I see that this is continuously updated, but am not sure why versions of PHP aren't updated as well.

**Comment by masroore** [comment]
I am using PHP 7.2.9 with laragon (v3.3 IIRC) with no problems at all.

**Comment by leokhoa** [comment]
@Swiftnesses : I've released Laragon 3.5. It should work smoothly with PHP 7.2 (tested with PHP 7.3 also)
@diomed : because you can add any PHP version yourself: https://forum.laragon.org/topic/166/tutorial-how-to-add-another-php-version
