### ISSUE TITLE
Laragon 5: Symantic detect malware

### ISSUE THREAD

**Issue by SocolaDaiCa** [leokhoa/laragon#250]
![image](https://user-images.githubusercontent.com/18243451/119918406-9623ef80-bf92-11eb-86d9-a3223a89d0c0.png)

**Comment by leokhoa** [comment]
@SocolaDaiCa 
https://www.virustotal.com/gui/file/4121e59790ccefd6554c2bf7d52f99b7219f696cb0bb62aa46a40f9bbad3ae65/detection
It is false alarm as Laragon 5 is new. Please help to check with other AV.

**Comment by leokhoa** [comment]
@SocolaDaiCa
Also please help to submit directly to their site for false positive check:
https://symsubmit.symantec.com/

**Comment by leokhoa** [comment]
In any case, if you believe the report is in error, please report a bug to the supplier of your virus scanner.
Many Windows binaries have the same issue because of AV mistake.
Ref: https://golang.org/doc/faq#virus

**Comment by leokhoa** [comment]
@SocolaDaiCa They've confirmed it is a false alarm. 
![image](https://user-images.githubusercontent.com/9049575/119997667-29dcd680-bffa-11eb-8367-9d99db7c05db.png)

**Comment by SocolaDaiCa** [comment]
@leokhoa great, thank you
