### ISSUE TITLE
Will Laragon release a version with PHP7.4, Composer 2, Node 14?

### ISSUE THREAD

**Issue by kidino** [leokhoa/laragon#261]
I know users can update these themselves. I did. But I think it's about high time now that Laragon releases a version with at least :

- PHP7.4
- Composer 2
- Node 14

A stable PHP8 version is also appreciated.

**Comment by leokhoa** [comment]
@kidino : You can check Laragon 5 release:
https://forum.laragon.org/topic/2425/laragon-5-0-released-quick-linux-server

**Comment by kidino** [comment]
Oh cool. I was browsing around this repo looking for something like that. I guess I missed it. Thanks.
