### ISSUE TITLE
Need support for Windows 11

### ISSUE THREAD

**Issue by anburocky3** [leokhoa/laragon#265]
Laragon Forum link: https://forum.laragon.org/topic/2555/ui-problem-on-windows-11-screenshot-attached/2
![](https://i.imgur.com/TJUoXHE.png)

**Comment by leokhoa** [comment]
Thanks @anburocky3 
Is it only the UI problem or is there another issue?

**Comment by anburocky3** [comment]
Currently notified only this error. 

Maybe if I found any in the future, will file a new issue in this repository.

**Comment by leokhoa** [comment]
I see an image near the close button (on the top right). Is it normal?

**Comment by leokhoa** [comment]
Gotchas, thanks.

**Comment by anburocky3** [comment]
![image](https://user-images.githubusercontent.com/15264938/132384380-7cee6c79-0d77-4705-a9dc-e943d1e094f9.png)

Check the padding of the menus, there is no padding on top & bottom.

**Comment by petersteele111** [comment]
I mean honestly this is really a non issue. I have been running Laragon on my Win 11 PC since the first dev channel release and it has been running and working perfectly. There are no major UI glitches or bugs and everything is running as it should. If winx64 is the only issue, then is it really worth putting in the time to fix? Its just a nice to have, not a breaking change or update.

**Comment by anburocky3** [comment]
@petersteele111  This is not indeed the functionality bug. It is just a UI bug and I think, it can be fixed with small work. If a newbie comes and sees this, he might think, that laragon has issues and is outdated.

@leokhoa Also, I noticed one thing, even most windows apps are lacking this padding. Check Bittorrent below,

![image](https://user-images.githubusercontent.com/15264938/132529519-4ce72208-e607-4f4f-a266-6d72f5e9522c.png)

**Comment by anburocky3** [comment]
**Update:** I don't know why, i restarted and suddently i noticed that, the UI problem is not appearing after a restart. @leokhoa  
![image](https://user-images.githubusercontent.com/15264938/133328055-293104c0-48bc-480a-8442-380d78a81f65.png)

Congrats, Laragon runs as usual in Windows 11 without any problem, so far.
