### ISSUE TITLE
Menu > PHP > Extensions: "Menu index out of range"

### ISSUE THREAD

**Issue by kedniko** [leokhoa/laragon#269]

**Comment by nikoked** [comment]
I've found the cause of this problem. This happened because I renamed `php.ini-development` to `php.ini` in `C:\laragon\bin\php\php-8.0.11-Win32-vs16-x64`

`laragon.log`

```
2021-09-30 02:39:23: File not found!: C:\laragon\bin\php\php-8.0.11-Win32-vs16-x64\php.ini-development
2021-09-30 02:39:50: There is an exception: Menu index out of range
```

**Comment by anchetaWern** [comment]
@kedniko hello. i'm having the same issue. how did you solve this?

**Comment by kedniko** [comment]
Make sure these files exists and are valid
`laragon/bin/{php-version}/php.ini`
`laragon/bin/{php-version}/php.ini-development`
`laragon/bin/{php-version}/php.ini-production`

If not, just download them here
https://www.php.net/downloads.php
https://www.php.net/releases/
or if you are using Windows...
https://windows.php.net/download
https://windows.php.net/downloads/releases/archives/
