### ISSUE TITLE
Default new mysql db charset

### ISSUE THREAD

**Issue by n-osennij** [leokhoa/laragon#27]
By default laragon create new mysql db (when Quick create project) with latin1_swedish_ci. How can I change it? How can set to new utf8mb4 charset?

**Comment by leokhoa** [comment]
@n-osennij ,

This link should help:
https://mathiasbynens.be/notes/mysql-utf8mb4

In Laragon, you open my.ini in (**Menu > MySQL > my.ini**)

**Comment by n-osennij** [comment]
thanks!
