### ISSUE TITLE
Source Code For Exe

### ISSUE THREAD

**Issue by MrGiga** [leokhoa/laragon#28]
Any plans on releasing it? I would love to take a look at your work and see if I can help.

**Comment by binksxela** [comment]
I agree with @MrGiga, like this everyone could review the code and contribute to it.

**Comment by MrGiga** [comment]
@leokhoa What's the official response to this?

**Comment by leokhoa** [comment]
@MrGiga : I managed to close old issues to focus on necessary ones. I had an answer here: https://forum.laragon.org/topic/123/laragon-why-it-is-not-open-source

You can also support Laragon by giving a GitHub star ★ and spread the word.

**Comment by W9JYD** [comment]
Sorry, @leokhoa you are in violation of the GPL. Apache is GPL. You CANNOT do this.
