### ISSUE TITLE
Ngrok AuthToken Setting

### ISSUE THREAD

**Issue by mr-chetan** [leokhoa/laragon#282]
Ngrok gives the following screen when i share it with laragon.
Already configure token as recommended by ngrok.

![image](https://user-images.githubusercontent.com/56998650/150185879-f9a73547-2ea1-40a3-9c81-60cb57549439.png)

**Comment by rivman** [comment]
Hello. Same issue here. Laragon create .yml file with the name of the local host, like mydomain.test and generate mydomain.test in the /bin/ngrok/conf folder. Even my Pro auth token is set in .ngrok2/ngrok.yml, it is ignored by Laragon, that my start ngrok (with "Share" command) with a specific .yml config file, making ngrok ignore the default config (used for authentication). 
Can a setting be make in Laragon settings to be able to put `# in ngrok.yml
authtoken: .......` and be used with share ? 

Many thanks.

**Comment by jade-creator** [comment]
> Ngrok gives the following screen when i share it with laragon. Already configure token as recommended by ngrok.
> 
> ![image](https://user-images.githubusercontent.com/56998650/150185879-f9a73547-2ea1-40a3-9c81-60cb57549439.png)

I have to set the **authtoken** manually in the project's .yml config file. The only problem I got was the forwarding URL leads me to _localhost/index.php_ (Laragon's Getting Started page) and not to my project.

**Comment by StAlKeRxXl** [comment]
Yes, it would be good if you specify a token in token_for_all_local_domains.yml (😉) - and Ngrok constantly used it for all domains...

**Comment by leokhoa** [comment]
@hj-collab 
What about it?
https://forum.laragon.org/topic/167/tutorial-how-to-share-your-projects-with-ngrok

**Comment by jpyrat** [comment]
> https://forum.laragon.org/topic/167/tutorial-how-to-share-your-projects-with-ngrok

Can't reach this URL :(

**Comment by atharalipk** [comment]
> @hj-collab What about it? https://forum.laragon.org/topic/167/tutorial-how-to-share-your-projects-with-ngrok
page not exist, 404 :(

**Comment by realtebo** [comment]
I cannot understand.
Every time I share from laragon with ngrok, the specific .yml  file is resetted,
So I cannot add the following line, because at every restart of ngrok via laragon, the .yml file is lost

    authtoken: UUxqXac...................SxaA

**Comment by devserge** [comment]
Did anyone got a solution for this problem? The yml file for the domain is keep being changed, because the port of the web addr is changing. Because of that, I can not add the authtoken to the config file. Filled in the authtoken in laragon gui, but that also didn't changed anything. Any suggestions or solutions here?

**Comment by realtebo** [comment]
I simply downloaded ngrok from the website in a new folder, and manually used them. Sorry, no fix found, only this workaround

**Comment by ronmarasigan** [comment]
Still no fix?

**Comment by easyconnect83** [comment]
Hello,
after doing some tests I realized that you just had to enter the Authtoken API key on the Laragon interface.
Menu/www/share/YourAuthtoken
Thus the key is kept in the yml configuration file of the project.

![laragon-ngrok](https://user-images.githubusercontent.com/36700921/224184664-a64d7c8c-214a-4162-bc5b-ef2ebf245a62.png)

**Comment by creyeschaponan** [comment]
Muchas gracias, thanks!!

**Comment by darmariduan** [comment]
> Hello, after doing some tests I realized that you just had to enter the Authtoken API key on the Laragon interface. Menu/www/share/YourAuthtoken Thus the key is kept in the yml configuration file of the project. > > ![laragon-ngrok](https://user-images.githubusercontent.com/36700921/224184664-a64d7c8c-214a-4162-bc5b-ef2ebf245a62.png)

I have followed your instructions and updated ngrok, and entered my personal token in my laragon. But this has not solved my problem, when I access the link provided ngrok appears as shown below.
![ngrok_6022](https://github.com/leokhoa/laragon/assets/38715500/685a1bac-b54e-418e-8a3c-d19622ce8c4b)

**Comment by donejeh** [comment]
> > Hello, after doing some tests I realized that you just had to enter the Authtoken API key on the Laragon interface. Menu/www/share/YourAuthtoken Thus the key is kept in the yml configuration file of the project. > > ![laragon-ngrok](https://user-images.githubusercontent.com/36700921/224184664-a64d7c8c-214a-4162-bc5b-ef2ebf245a62.png)
> 
> I have followed your instructions and updated ngrok, and entered my personal token in my laragon. But this has not solved my problem, when I access the link provided ngrok appears as shown below. ![ngrok_6022](https://user-images.githubusercontent.com/38715500/267852292-685a1bac-b54e-418e-8a3c-d19622ce8c4b.jpg)

Just ngrok download ngrok from their website and this command 

` http --host-header=<your_domain_name> 80 
`
**NOTE:** dont include http eg _ngrok http --host-header=laravelbackend.test 80_ 

@ronmarasigan @realtebo

**Comment by darmariduan** [comment]
> > > Hello, after doing some tests I realized that you just had to enter the Authtoken API key on the Laragon interface. Menu/www/share/YourAuthtoken Thus the key is kept in the yml configuration file of the project. > > ![laragon-ngrok](https://user-images.githubusercontent.com/36700921/224184664-a64d7c8c-214a-4162-bc5b-ef2ebf245a62.png)
> > 
> > 
> > I have followed your instructions and updated ngrok, and entered my personal token in my laragon. But this has not solved my problem, when I access the link provided ngrok appears as shown below. ![ngrok_6022](https://user-images.githubusercontent.com/38715500/267852292-685a1bac-b54e-418e-8a3c-d19622ce8c4b.jpg)
> 
> Just ngrok download ngrok from their website and this command
> 
> `http --host-header=<your_domain_name> 80 ` **NOTE:** dont include http eg _ngrok http --host-header=laravelbackend.test 80_
> 
> @ronmarasigan @realtebo

Thank you for your help, it worked for me.

**Comment by PLAYGEANT** [comment]
I have the same problem but I found a solution, you must just go in the same menu but choose a region. After your had choose a region, it works !
