### ISSUE TITLE
New exemplar of laragon

### ISSUE THREAD

**Issue by n-osennij** [leokhoa/laragon#29]
Windows 10 latest

When auto create laravel (quick create) laragon open new  laragon exemplar. So in tray I can see 2 laragon icons

**Comment by leokhoa** [comment]
Hi @n-osennij ,
Sorry, I'm not sure what do you mean?

**Comment by n-osennij** [comment]
![p3hfdk9sqq](https://user-images.githubusercontent.com/17576299/44616231-ae500880-a854-11e8-958d-063a0ca12fa5.gif)
I make a gif to show you. Look at the tray (left bottom). I have only one icon of laragon there. But when process of installing laravel is finished - two icons.

**Comment by leokhoa** [comment]
I still can not reproduce this so I will close the issue. You can try the latest version of Laragon. If the issue still persist, let me know.
