### ISSUE TITLE
How to upgrade redis version

### ISSUE THREAD

**Issue by richwxd** [leokhoa/laragon#294]
Recent version of redis-windows pre-compiled is 5.0.14.1, but when I put this one to bin\redis directory, there is not a version choice for redis. It is always 3.2.100. This version I found sometimes there are strange errors on windows and must restart redis-server to resolve. So that is why I always use an recent version of redis. Please give a help on it.

**Comment by leokhoa** [comment]
@richwxd 
You can update Redis version in laragon.ini yourself:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/9049575/157264843-43897149-9f21-4b23-a125-228c0f343146.png">

**Comment by richwxd** [comment]
Hi,

Thanks a lot!
