### ISSUE TITLE
unsatisified

### ISSUE THREAD

**Issue by bckelley** [leokhoa/laragon#297]
This program is now complete crap! maybe update the project to a language more relevant than Delphi!

**Comment by solarpolar** [comment]
Well.. it's OpenSource... so if you feel like it, you re-write it!

**Comment by leokhoa** [comment]
@bckelley: What's wrong?
Your sound looks hatred

**Comment by bckelley** [comment]
> 

It's not. look at the code it's an exe file. can't edit that
