### ISSUE TITLE
Problem: WordPress setup using QuickApp is not working

### ISSUE THREAD

**Issue by PauloCarrasco** [leokhoa/laragon#305]
Hi.

I've found out that the WordPress Quick App is not working as it should. I'm getting this error:

![image](https://user-images.githubusercontent.com/1708828/164674736-1d596b6c-5bcc-44f8-ad1c-3bae1909c795.png)

I've the following url in [sites.conf]:  https://wordpress.org/latest.tar.gz
 
I can download it without any problem through any browser. Then I tested directly in the command line using cUrl and found out that using:

    curl -O https://wordpress.org/latest.tar.gz
 
It gave the following error:

    curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

So I added the **--ssl-no-revoke** parameter 

    curl -O --ssl-no-revoke https://wordpress.org/latest.tar.gz

And it downloaded without any error. 

I guess there is a problem with the way the Quick App downloads the tar.gz file. If it uses cUrl there may be a certificate problem that needs to be fixed or the --ssl-no-revoke parameter that is missing.

My setup:

    Laragon Full 5.0.0.210523
    OS Name Microsoft Windows 10 Pro
    Version 10.0.19044 Build 19044
    Locale United States
    Keyboard: pt-PT

**Comment by leokhoa** [comment]
Thanks @PauloCarrasco 
This has been improved with Laragon 6.0:
https://github.com/leokhoa/laragon/releases/tag/6.0.0
