### ISSUE TITLE
Contrast for Laragon 6.0.0 black on blue incorrect

### ISSUE THREAD

**Issue by Pen-y-Fan** [leokhoa/laragon#330]
Great job on the [Laragon 6.0.0](https://github.com/leokhoa/laragon/releases/tag/6.0.0)!

The most noticeable problem is the contrast ratio when selecting a menu see picture:

<https://i.imgur.com/MtYASaY.png>

I like the dark blue background, but In my opinion, the text should be white or light grey, on the blue background.

The black text with a dark blue background is not clear.

**Comment by RobiNN1** [comment]
It doesn't look good at all in Windows 11. Even icons are hidden on hover. Also, the fonts are sometimes a bit blurry, like that new Donate text.

I think if the author finally releases Laragon as open source, there will be many people who will fix all these annoying problems. But according to many posts, this will never happen.

**Comment by leokhoa** [comment]
@Pen-y-Fan : Thank you for your information. I didn't change anything related to style on Laragon 6. I'll check and fix that.

@RobiNN1 : It is just a small issue related to Windows 11. I don't want bad people inject malicious code to Laragon. Many risks over benefits.

**Comment by RobiNN1** [comment]
@Pen-y-Fan in new Win 11 22h2 update it's fixed. They basically added back compatibility for old UIs
