### ISSUE TITLE
Laragon using PHP installed on system instead of its own bundled PHP.

### ISSUE THREAD

**Issue by apokaliptis** [leokhoa/laragon#34]
Hello, I'm on windows 10 and I installed the latest version of Laragon on my D:\ drive. I was trying to run a site I'm working on but it kept telling me the mbstring extension was not installed, even though the it was enabled in the php.ini and tray menu icon for Laragon confirmed it. When I checked phpinfo() mbstring didn't show up and the following test code for mbstring gave a failed response:
```
<?php
if (extension_loaded('mbstring')) { echo "Success"; }
else { echo "Fail"; }
```
Well, it turns out the PHP installation the server was loading was the one I installed using [scoop](https://scoop.sh/). After removing mt PHP installation everything started working properly.

**Comment by leokhoa** [comment]
Nice, I am glad to hear it worked. I will take a look on that.
