### ISSUE TITLE
Laragon.org webpage not reachable

### ISSUE THREAD

**Issue by petrsimunek** [leokhoa/laragon#342]
Hello,

I wanted to download laragon recently, so I navigated to laragon.org, but the site is not reachable for me. I get ERR_CONNECTION_REFUSED in chrome.
I tried different PC on different connectivity, even one with VPN, but still the same error.

I hope laragon is not dead. :(

Thanks

![image](https://user-images.githubusercontent.com/49954958/201510605-b10fe674-ea77-4891-972b-eb827d5dbb42.png)

**Comment by madebyaris** [comment]
Same here, I can't access laragon.org, and event the subdomains are down right now.

Hope, the dev can bring it back ASAP.

**Comment by JurriaanK** [comment]
@leokhoa laragon.org is down since at least last Friday.

**Comment by petrsimunek** [comment]
Anyway, I used the link on github, to get 6.0.0 release here: [https://github.com/leokhoa/laragon/releases/download/6.0.0/laragon-wamp.exe](https://github.com/leokhoa/laragon/releases/download/6.0.0/laragon-wamp.exe)

... but anyway. I was just worried. Author has status on the profile, that he is on vacation. :)

**Comment by asheavenist** [comment]
Yes.. I can't access the web from OperaGX too. Try access it with VPN, and there is no result.

**Comment by JagMolar** [comment]
> Anyway, I used the link on github, to get 6.0.0 release here: https://github.com/leokhoa/laragon/releases/download/6.0.0/laragon-wamp.exe
> 
> I was just worried. Author has status on the profile, that he is on vacation. :)

It may be that all of us should be on vacations in Ibiza...and enjoy with him of it... 😂.
At moment we can use the link and resolve momently.

**Comment by leokhoa** [comment]
Sorry guys, the Cloud hosting has suspended my account because no payment. I am working on it.

**Comment by ashik-ahmed-dev** [comment]
https://github.com/leokhoa/laragon/releases/download/6.0.0/laragon-wamp.exe

**Comment by GoMoSoLo** [comment]
> Sorry guys, the Cloud hosting has suspended my account because no payment. I am working on it.

Good luck Leo, hopefully the hosting Co will resolve it today - I feel like I have lost one arm! Good luck Sadie

**Comment by leokhoa** [comment]
I has moved it to AWS. It's up & running now.
