### ISSUE TITLE
pgAdmin is not showing up in Menu>PostgreSQL

### ISSUE THREAD

**Issue by aptco** [leokhoa/laragon#345]
pgAdmin is not showing up in Menu>PostgreSQL after PostgreSQL is installed from Menu>Tools>Quick add.
Laragon version is 6.0.220916.
I see it in the menu on tutorial sites like this one. (https://www.kreaweb.be/laragon-add-postgresql/)
Is there a conf file for Menu/RightClickMenu that can enabled it?

**Comment by curtis18** [comment]
I face the same issue as well.

**Comment by leokhoa** [comment]
@aptco , @curtis18 : pgAdmin is so slow so it is removed to encourage using Dbeaver.
You can add Dbeaver in **Menu > Tools > Quick add > Dbeaver**

**Comment by aptco** [comment]
> @aptco , @curtis18 : pgAdmin is so slow so it is removed to encourage using Dbeaver. You can add Dbeaver in **Menu > Tools > Quick add > Dbeaver**

I couldn't find Dbeaver in Quick add but it showed up after adding dbeaver source to packages.conf.
After installing it, it showed up under the PostgreSQL menu. Thanks!

**Comment by mrsmartchoice** [comment]
After successful installation but I can't see PG admin

**Comment by Yasinrabiee** [comment]
dbevear is very old🙁
