### ISSUE TITLE
portable with updated php ?

### ISSUE THREAD

**Issue by beppe9000** [leokhoa/laragon#35]
i see on the website only php 5.6 is included in the portable version. I would like to use php 7.2.
is there a portable release with that php version for download somewhere?

**Comment by beppe9000** [comment]
Thanks, i will follow that post!

**Comment by leokhoa** [comment]
@beppe9000 : With Laragon 4.0, you have "Quick Add" to make the process quicker.
https://forum.laragon.org/topic/1204/laragon-4-0-released-with-quick-add-feature
