### ISSUE TITLE
Upgrade to MySQL 8 / MariaDB 10.2

### ISSUE THREAD

**Issue by murzid** [leokhoa/laragon#36]
Please upgrade the DBMS to MySQL 8 / MariaDB 10.2 👍 

Because those version has supported "Window Function"
- https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html
- https://mariadb.com/kb/en/library/window-functions/

My project doesn't work with MySQL 5.7 or MariaDB 10.1

Thanks

**Comment by murzid** [comment]
Really life saver, Super Duper Easy 👍 
Everything can be update / upgrade so easily

Thanks @leokhoa and Laragon 😄

**Comment by Paul75** [comment]
Hello,

Sorry but not works with mysql 8.0.13, failed ...


Thanks

**Comment by leokhoa** [comment]
@murzid : I've released Laragon 4.0 which make the process even easier:
https://forum.laragon.org/topic/1204/laragon-4-0-released-with-quick-add-feature

@Paul75 : I tested it worked fine with MySQL 8.0.13 and MariaDB 10.3

**Comment by murzid** [comment]
So many many thanks to @leokhoa

Laragon more powerful than before with this latest update

#ByeByeXampp

**Comment by smplyjr-dev** [comment]
How I wish someone would write a step by step guide here on how to update the MySQL version as the Laragon's forum seems unreachable. 👍

**Comment by leokhoa** [comment]
@smplyjr-dev : There was a high load that caused issue to Laragon's forum. It may happen again but no worries, I have a plan to move hosting next year.
