### ISSUE TITLE
Clicking "Terminal" with Cmder Does Nothing

### ISSUE THREAD

**Issue by MrGiga** [leokhoa/laragon#37]
If you have Cmder active and click the Terminal button on Laragon, no terminal window appears. You are forced to close all instances of Cmder to get the terminal button to function correctly.

**Comment by leokhoa** [comment]
@MrGiga : Thanks for pointing out. Let me check and get back to you soon.

**Comment by leokhoa** [comment]
@MrGiga : I've fixed it in Laragon 4.0:
https://forum.laragon.org/topic/1204/laragon-4-0-released-with-quick-add-feature

**Comment by MrGiga** [comment]
Issue currently exists with 4.0.4

1. Open Installed version of Cmder
2. Click Terminal Button

Result: Cmder window opened in Step 1 flashes
Expected Result: Terminal window opens with access to contents of www folder
