### ISSUE TITLE
After upgrade to 3.5.1 there is no option for Ngrok

### ISSUE THREAD

**Issue by pjadanowski** [leokhoa/laragon#38]
Can't see Ngrok option when right click on main window. I found somewhere else option for sharing with ngrok but without options like setting Region

**Comment by leokhoa** [comment]
@pjadanowski : It's on **Menu > www > Share > Region**

**Comment by pjadanowski** [comment]
sorry i don't have "www" option
![screenshot_49](https://user-images.githubusercontent.com/16418436/48150474-1b553500-e2bf-11e8-805d-c39910901b07.png)

**Comment by leokhoa** [comment]
@pjadanowski : It's on **Menu > www > Share > Region**
