### ISSUE TITLE
Server started with wrong IP?

### ISSUE THREAD

**Issue by SonnyDAscola** [leokhoa/laragon#39]
Hey,

I've just tested laragon for the first time and had a problem right away.
Due to some changes in my system, laragon started server with the wrong IP. 
It is using the VirtualBox-HostOnly IP/Adapter.

I haven't found any way to solve this or configure it. Is there a way to do so? (it uses 192.168.56.1 and not 192.168.1.2 like it should)

**Comment by leokhoa** [comment]
@SonnyDAscola : Thanks for pointing that out. It does not affect the functionalities of Laragon so I did not notice about that. I'll fix it soon.

**Comment by SonnyDAscola** [comment]
Thank you for fixing :) great project anyway (deactivated the VBox-adapter with laragon startup for now)

A main reason this should be configurable could be usage within vpns as well as usage with possible bulks of networking-devices.

Therefore - extended functionality? 
Anyway - Thank you very much!

**Comment by leokhoa** [comment]
@SonnyDAscola : My pleasure - I've released Laragon 4.0 which will display right IP. The new algorithm takes time so it will display asynchronously.
You can download and install it over your current Laragon:
https://forum.laragon.org/topic/1204/laragon-4-0-released-with-quick-add-feature

**Comment by SonnyDAscola** [comment]
@leokhoa wonderful! It works perfectly by now. Thank you very much!

**Comment by leokhoa** [comment]
@SonnyDAscola: Cheers!
