### ISSUE TITLE
Public IP Address Availability

### ISSUE THREAD

**Issue by SHSharkar** [leokhoa/laragon#42]
Hello @leokhoa and thanks for your services.

I would like to know, instead of assigning the projects to a **Local domain** or **Local development IP** addresses is there any possibility to add **Public IP** and **Public domain** facility so that projects can be accessed through **World Wide Web**.

Looking for your kind of response.

Thanks.

**Comment by leokhoa** [comment]
@shsbd : @skwalgit is right, you can share your projects through the WWW easily with 1 click using **Menu > www > Share**
https://laragon.org/docs/quick-share.html

**Comment by shsbd** [comment]
I have accessed to location

```shell
ConfigPaths | Y:\laragon\bin\ngrok\conf\my-xyz-project.yml
```

For checking my projects ngrok configuration. Here I have manually attached the `authtoken` to the `my-xyz-project.yml` which is `ngrok` config file. After the assignment, I have to restart the `ngrok share` and found:

![image](https://user-images.githubusercontent.com/12555542/48532759-e69f3a00-e8cb-11e8-8bf4-c181cc14de9a.png)

After giving the `authtoken` manually to the `yml` file, `ngrok` runs with my account. But this is not an efficient and permanent solution. Like if I change the project folder or the domain, it will change. If you could do a permanent solution for this or store the `authtoken` configuration to somewhere else and call globally every time when `ngrok` starts sharing, that would be a great and permanent solution.

I already added the `ngrok` configuration file to my `$HOME` location but no luck.
