### ISSUE TITLE
Composer windows incompatible.

### ISSUE THREAD

**Issue by otavio-araujo** [leokhoa/laragon#425]
When I try any composer commands, I got the message:

This version of C:\laragon\bin\composer\composer.exe is not compatible with the version of Windows you are running. Check your computer's system information and contact the software vendor.

Does anyone knows what to do?

**Comment by eagleuk** [comment]
Devil is in the details.

Tell us what Windows version you are actually running and what build.

Worked fine on a fresh install of v5 for me.

If you aren't already on windows 10/11 then that's the place to start.

I can't foresee this being a laragon specific issue so you so imagine this issue should be closed. 

If it allows you, you can try and update composer too.

**Comment by otavio-araujo** [comment]
> Devil is in the details.
> 
> 
> 
> Tell us what Windows version you are actually running and what build.
> 
> 
> 
> Worked fine on a fresh install of v5 for me.
> 
> 
> 
> If you aren't already on windows 10/11 then that's the place to start.
> 
> 
> 
> I can't foresee this being a laragon specific issue so you so imagine this issue should be closed. 
> 
> 
> 
> If it allows you, you can try and update composer too.
> 
> 
> 
> 
> 
> 
> 
>

**Comment by otavio-araujo** [comment]
Thank you!

I've Just fresh reinstalled Windows...
Its working again!

Thank you!

**Comment by eagleuk** [comment]
Don't forget to close the issue 👍
