### ISSUE TITLE
mysqli extension is missing if the default configuration...

### ISSUE THREAD

**Issue by andrii-marushchak** [leokhoa/laragon#428]
I just installed Laragon with default PHP 8.1
mysqli extenstion is enabled,  and i see it with `phpinfo()
`

but in the adminer or phpmyadmin I see erorrs

![image](https://user-images.githubusercontent.com/31574759/222931499-57000f5d-ebc7-43cd-bec4-326c216a4eb8.png)
![image](https://user-images.githubusercontent.com/31574759/222931580-f207db9b-35fe-469d-88dc-971dd8fa05d5.png)
![image](https://user-images.githubusercontent.com/31574759/222931583-536ea5e8-7a1b-46e8-885c-171edf2f6726.png)

**Comment by josealgardataborges** [comment]
It's working well here, did you change anything from default instalation?

![image](https://user-images.githubusercontent.com/8929655/225868589-b9b9c24f-fe99-44ed-b463-d4c07ec16f6f.png)

**Comment by andrii-marushchak** [comment]
it was issue related to WSL2 enabled with mysql

**Comment by abletec** [comment]
It'd really be helpful if you explained precisely what you did to resolve your problem. Looks like I have the same 1. :(.

**Comment by abletec** [comment]
I solved it. In the php.ini file of the PHP version you're using, replace:
   extension=mysqli
with the full extension pat. In my case, that was:
extension="d:\laragon\bin\php\ext\php_mysqli.dll"

HTH someone.

**Comment by hiepvq** [comment]
@abletec works for me
