### ISSUE TITLE
how to delete item from menu

### ISSUE THREAD

**Issue by zcyc** [leokhoa/laragon#47]
when i use Menu > Tools > Quick add > All
i dont need some pkg
then i delete it from X:\laragon\bin
now there always a button in laragon Tools
how can i remove it
can you add a ini file to setting all menus in laragon
maybe we can add more useful button and remove some unuseful button from it

**Comment by charliezzo** [comment]
laragon is so cool for developer
hope your more dev tools for us
maybe you can make another pkg manager more userful than chocolatey for developer
