### ISSUE TITLE
Using Quick App or Quick Add gets stuck on downloading

### ISSUE THREAD

**Issue by insanetesterftw** [leokhoa/laragon#48]
When adding WordPress using Quick App or using Quick Add the application gets stuck on the downloading screen. It downloads things in the background and then nothing.

![image](https://user-images.githubusercontent.com/11148841/50091748-18295f00-0204-11e9-9d50-6969427db4da.png)

Using the most recent install version and the most recent portable version. On Windows 7 64-bit.

**Comment by leokhoa** [comment]
@insanetesterftw : Did you try Proxy?
https://forum.laragon.org/topic/1226/tutorial-how-to-sort-out-download-issue-using-proxy

**Comment by Venrir** [comment]
you should be in need to add a proxy in first place to download via direct link.
im having the same problem, downloaded an updated curl from somewhere and it worked somehow.
The file ur looking to replace is .\bin\laragon\utils\curl.exe

**Comment by insanetesterftw** [comment]
@leokhoa 
As I said the files are downloaded behind the scenes. But the interface is stuck on **downloading**.

Previous versions of laragon worked with the exact same variables. Computer, operating system and internet settings. The new version doesn't work.

**Comment by canhkieu** [comment]
Same problem.

**Comment by pablobb** [comment]
same here :(

**Comment by morvy** [comment]
As said, replace curl.exe, certificate and libcurl-x64.dkk with files from this link:
https://curl.haxx.se/windows/

**Comment by leokhoa** [comment]
@morvy , @pablobb, @canhkieu , @insanetesterftw , @Venipa : It is a strange issue. However, I developed a fallback download method to sort out the issue. If you guys are having the issue, just update Laragon version to 4.0.9:
https://forum.laragon.org/topic/1204/laragon-4-0-released-with-quick-add-feature?page=1

**Comment by Venipa** [comment]
well its not done yet
![](https://i.mavis.moe/f/EzNGeXxP3t/laragon-2019-02-26-09-40-56.png)

**Comment by morvy** [comment]
@Venipa we are on 4.0.11 release already ...

**Comment by leokhoa** [comment]
@morvy : Do 4.0.11 work for you?

**Comment by Venipa** [comment]
@morvy @leokhoa i tried 4.0.11 before it had the same error message

**Comment by morvy** [comment]
If I don't have problems with database password, this feature works for me. But as I mentioned earlier, I replaced some CURL files when upgrading to 4.0.5

4.0.10
![image](https://user-images.githubusercontent.com/1279809/53401219-c1809400-39af-11e9-9652-925bbe16434b.png)

4.0.11
![image](https://user-images.githubusercontent.com/1279809/53401437-16240f00-39b0-11e9-805e-4a25f4d27f02.png)

**Comment by leokhoa** [comment]
@Venipa , @morvy : I've fixed it. Please update to Laragon 4.0.12:
https://forum.laragon.org/topic/1232/tutorial-how-to-upgrade-to-laragon-4-x-from-former-versions-laragon-3-x/2

**Comment by morvy** [comment]
I get this trying to add apache

![image](https://user-images.githubusercontent.com/1279809/53673070-c54d3880-3c85-11e9-8572-d58830272e95.png)

**Comment by leokhoa** [comment]
@morvy : I fixed the issue in Laragon 4.0.12 **190228**

**Comment by morvy** [comment]
You're right, I had 4.0.12 190227 :D
