### ISSUE TITLE
Website Zertifiicate expired

### ISSUE THREAD

**Issue by DockerComposeFiles** [leokhoa/laragon#485]
Laragons Website Zertificate Expired YesterYesterday
![image](https://user-images.githubusercontent.com/87118951/235289901-bcfba7af-2715-4f08-98c4-8aa2d16c43e8.png)

Please confirm that the website has not hacked.

**Comment by jpyrat** [comment]
Same here !

**Comment by skino2019** [comment]
i think he mentioned something about moving his site stuff across to GitHub only.
