### ISSUE TITLE
Reduce the number of notifications In Windows

### ISSUE THREAD

**Issue by srcek** [leokhoa/laragon#5]
I really like Laragon and use it professionally. Fastest dev environment out there.
But, could you please reduce the number of notifications in Windows action center. It really is overwhelming if you open and close Laragon controls often. Or at least offer a way to turn them off.

**Comment by leokhoa** [comment]
@srcek : No problem. I'll make it display only at the first time running.

**Comment by leokhoa** [comment]
@srcek : Can you check the latest version of Laragon. It should work as you expect.
