### ISSUE TITLE
REMOVE ALL CACHE PLEASE

### ISSUE THREAD

**Issue by DonKolia** [leokhoa/laragon#583]
Where? I have very very very very cache in everything, in the web and sql.
I have tried browsers in incognito window and I always have cache and I don't see the changes, even in basic HTML websites.
I can remove tmp folder?

**Comment by leokhoa** [comment]
@DonKolia: tmp folder can be removed. You should specify your issue in more details so people can help.

**Comment by DonKolia** [comment]
This is my problem, i have cache everywhere. In the SQL, in CSS, in JSON, in everywhere

**Comment by DonKolia** [comment]
I am watching my old pages, is impossible for me see the changes.
![image](https://github.com/leokhoa/laragon/assets/55564649/1552aeea-92fc-4876-aaee-6744253b3693)
Is weird this.

**Comment by DonKolia** [comment]
Okay, i think it was Cloudfare cache:
![image](https://github.com/leokhoa/laragon/assets/55564649/28bb4512-7d9c-4829-b037-45a3d55fb751)
Now, instant update the changes. And i put this changes in .conf of my website.
![image](https://github.com/leokhoa/laragon/assets/55564649/bf5c5c25-f017-47a2-b298-45481501c2a5)
