### ISSUE TITLE
Complete tutorial of Laragon - MultiLang in 18 Languages

### ISSUE THREAD

**Issue by DonKolia** [leokhoa/laragon#595]
I have created a tutorial showing and teaching everyone Laragon.

CREATE PUBLIC WEB SERVER WITH SSL - OPEN PORTS | PHPMYADMIN | WORDPRESS | LARAVEL | SQL | MONGO
https://youtu.be/Cgtk-0X0ULw?si=28rraNum7ZdOkgFo

00:00 - Introduction
03:57 - Create first web page
04:27 - Simple program setup
06:10 - Start for the first time
06:38 - Create web page - Blank
07:44 - Set default folder to look at a folder
09:21 - First sample page with SSL by default
10:00 - Install phpMyAdmin
10:47 - Login to phpMyAdmin
10:55 - Create user in phpMyAdmin for MySQL
12:25 - Connect to Database - HeidiSQL
13:34 - Delete web page or database
14:16 - Create website - Wordpress
17:08 - Install SSL - Cloudfare or whatever
17:30 - Create SSL on Cloudfare
17:57 - Install SSL manually
18:56 - Declare SSL on sites-enabled
20:16 - Create website - Laravel
21:42 - Fix /public/ folder bug
22:42 - Create website - Symfony
24:58 - Install, enable PHP extension
25:38 - Install and enable Mongo
27:23 - Start Mongo - connect ECONNREFUSED 127.0.0.1:27017
28:21 - Create Mongo user
29:02 - Code to create user
29:41 - Execute code in console
29:59 - Open Firewall ports 443 and 80
30:40 - Opening ports in Firewall
33:14 - Set local IP Fixed or Static IP
37:16 - Open ports on router 80 and 443
42:02 - Setting your domain pointing to your IP in DNS Records
44:15 - Static or Dynamic IP
46:30 - Explanation and summary

**Comment by DonKolia** [comment]
I sent this ticket to you so that you can put the video and show it for new users who need to know how Laragon works.

**Comment by erobertsme** [comment]
Laragon is a local development tool. It should not be used to host a public website. If you are a person who needs a video tutorial to show you how to use Laragon or open ports on your router to host a public website, then it is particularly dangerous to host a website using your home network.

**Comment by DonKolia** [comment]
What is the difference between Nginx, MySQL in a company and in a home?
If you're a bitter jealous bastard, go cry.
