### ISSUE TITLE
PHP 8.3: httpd.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by 3xploiton3** [leokhoa/laragon#617]
![image](https://github.com/leokhoa/laragon/assets/19517680/1f9114c8-0da6-4349-87c9-071ca6e94ebb)

![image](https://github.com/leokhoa/laragon/assets/19517680/64412db0-7e92-4be3-b0bc-e25fa6377338)

**Comment by 3xploiton3** [comment]
**Solved**

Just update apache to 2.4.58

![image](https://github.com/leokhoa/laragon/assets/19517680/9dcd71ad-0c8f-40c3-835f-4e61577bd971)

**Comment by reihanboo** [comment]
just gonna drop the link to the binaries download page because apache's page is confusing 

https://www.apachelounge.com/download/
