### ISSUE TITLE
Laragon changes php from 7.4 to 8.1 but the system no?

### ISSUE THREAD

**Issue by danielchicote** [leokhoa/laragon#632]
I ussualy work with php 7.4.

In one moment i need to change and restart the server with 8.1. All correct, php info file shows correctly the new version, in laragon config appears the new version correctly loaded too.

But when i open the console, it says that is 7.4, and when i run a script in the server (after have restarted it), it gives me errors like if 7.4 still running.

WTF??

**Comment by TsKalandadze** [comment]
Have you tried "Add Laragon to Path" ? You can find it in Menu =>  Tools => Path 
It tells Windows where the PHP installation folder is.

**Comment by danielchicote** [comment]
Thanks, it was that!!

**Comment by flik** [comment]
Download php version from here as per Your OS 64bit or 32bit then try. [https://windows.php.net/downloads/releases/](https://windows.php.net/downloads/releases/)

It is working perfectly for me.

**Comment by KAUSHIK92-WEB** [comment]
Hi, when i do change the php version in laragon, and after restart the laragon server, but in cmd prompt not showing changed version. for that i have to do restart the system, so this is correct way to change version? or any right way?

**Comment by reinierbutot** [comment]
> Hi, @flik @danielchicote @TsKalandadze @reinierbutot @Viktorminator when i do change the php version in laragon, and after restart the laragon server, but in cmd prompt not showing changed version. for that i have to do restart the system, so this is correct way to change version? or any right way?

you need to right click the Laragon tray icon and start the terminal app from there. that is the terminal that automatically changes the php version. you default windows cmd does not change over the php version.

**Comment by KAUSHIK92-WEB** [comment]
thank you @reinierbutot

**Comment by KAUSHIK92-WEB** [comment]
hi, @reinierbutot 
okay, but we need to change environment variable path, when we change php version in laragon? specially for system terminal?

**Comment by vipinbatham** [comment]
use laragon terminal that will help u out.
