### ISSUE TITLE
Support for PHP 8.2

### ISSUE THREAD

**Issue by kevineduardo** [leokhoa/laragon#636]
Can we get it?

**Comment by RegalChivas** [comment]
yes you can! 
look this for editing packages >> [Quick Add](https://laragon.org/docs/quick-add.html) 

add this code in new line
`php_8.2.13=https://windows.php.net/downloads/releases/php-8.2.13-nts-Win32-vs16-x64.zip`

then install a new php with select on quick add

**Comment by kevineduardo** [comment]
For those wondering, there is this article also: https://medium.com/@leovn/how-to-add-another-php-version-to-laragon-a0f28ee32fd4
