### ISSUE TITLE
Laragon/Apache sites-enabled conf file not working.

### ISSUE THREAD

**Issue by lambo-developer** [leokhoa/laragon#699]
Hey, so I am working with Laragon and I wanna change the default root of my current project (not the entirety of Laragon) to a /public folder I have. When I go to laragon on my taskbar -> apache -> sites-enabled -> myproject.conf, I already have set the root to the /public folder;
```
<VirtualHost *:80> 
    DocumentRoot "C:/laragon/www/workopia/public"
    ServerName workopia.app
    ServerAlias *.workopia.app
    <Directory "C:/laragon/www/workopia">
```
Yet it still isn't working and is attempting to find a index.php in my :root dir, any ideas on how to get it to work and look inside my /public folder?

**Comment by kstingel** [comment]
@lambo-developer 
> [!CAUTION]
> hardcoding your project root will break portability

> [!TIP]
> take a look at `{Laragon Root}/usr/tpl/VirtualHost.tpl` for an example VirtualHost file which preserves portability

changes to `taskbar -> apache -> sites-enabled -> myproject.conf` won't help you here - 
Apache is looking for `auto.worktopia.{host tld}.conf` or `workopia.app.conf`

mapping the taskbar menu to filepath:
 `taskbar -> apache -> sites-enabled` will become `{Laragon Root}/etc/apache2/sites-enabled`

within that folder, you should see something similar to:
- `00-default.conf` (localhost)
- `auto.workopia.{host tld}.conf`
- `auto.{other-folder}.{host tld}.conf`
- `auto.{other-folder2}.{host tld}.conf`

1. open the `auto.workopia.{host tld}.conf` file in Notepad++
2. `File > Save As...` `workopia.app.conf` in `{Laragon Root}/etc/apache2/sites-enabled`
3. make your edits: <br> 
```shell
define SITE "workopia"
define ROOT "{Laragon Root}/www/${SITE}/public"

<VirtualHost *:<<PORT>>> 
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}
    <Directory "${ROOT}">
```
4.  `File > Save` the changes, leaving the file open
5. `File > Save a Copy As...` to `{Laragon Root}/usr/sites-enabled` to create a backup of your customised file

> [!WARNING] 
> Remember to *STOP Apache* and *START Apache* to apply changes!

@Pen-y-Fan can you confirm please?

**Comment by Pen-y-Fan** [comment]
When Laragon detects changes to the www directory the auto. .... .conf files are automatically re-created. Normally Laragon will check if you have a public folder and map the root. Does the public directory contain an index.php file? If so Laragon normally detects it. Im not sure **.app** can be used as a local tld. Try changing the Hostname template to **{name}.test** 

e.g.

<img width="399" alt="image" src="https://github.com/leokhoa/laragon/assets/40126936/0c5b6efc-215f-4c67-8a29-2ed68d4c8146">

Your document route and data directory will be the C: drive.

Then restart Laragon. 

Has Laragon created the entry for each app in your host file? Click the red H in the top right of Laragon to open your host file, you should see:

```text
127.0.0.1      workopia.test            #laragon magic! 
```

If your site still isn't detecting the public directory check for .htaccess files in the root and public directories, they may be causing conflicts with the auto-detection.

Please let us know how you get on.

**Comment by lambo-developer** [comment]
Hello, thanks for both the comments I really appreciate them.

I ended up doing what @kstingel said regarding my .conf file;
```
define SITE "workopia"
define ROOT "{Laragon Root}/www/${SITE}/public"

<VirtualHost *:<<PORT>>> 
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}
    <Directory "${ROOT}">
```
Nothing happened, the issue still persisted.

I switched from the .app to the .test and I checked my host file and this is what was added;
```
127.0.0.1      workopia.test        #laragon magic!   
```
However when I navigate to that route, it displays Laragon's default index.php that has the "getting started" button. My files are not displayed.
https://prnt.sc/dNYny_yh98xh

when I navigate to localhost/workopia it shows me the "List of directories"
https://prnt.sc/YZLX_evAAMX_


My current .htaccess file is in the /public folder with the following lines;
```
Options -Indexes

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php [NC,L,QSA]
```

However if I move it to my root folder, I get a "Forbidden, You don't have permission to access this resource";
https://prnt.sc/IHPNlTbF_E5C

Seems like a really weird issue, I scoured the internet for solutions but I haven't seen any issues close to mine.

**Comment by kstingel** [comment]
> Hello, thanks for both the comments I really appreciate them.
> 
> I ended up doing what @kstingel said regarding my .conf file;
> 
> ```
> define SITE "workopia"
> define ROOT "{Laragon Root}/www/${SITE}/public"
> 
> <VirtualHost *:<<PORT>>> 
>     DocumentRoot "${ROOT}"
>     ServerName ${SITE}
>     ServerAlias *.${SITE}
>     <Directory "${ROOT}">
> ```
snipped

my apologies @lambo-developer 
as a matter of course, I use `{Laragon Root}` as a placeholder for *your* Laragon install location

not everyone's Laragon install is located on `C:\` drive, as can be seen from the image from @Pen-y-Fan above :)
my intent was for you to replace the placholder with the correct Laragon root directory

> I've edited my preious comment to explain this

**Comment by kstingel** [comment]
> When Laragon detects changes to the www directory the auto. .... .conf files are automatically re-created. Normally Laragon will check if you have a public folder and map the root. Does the public directory contain an index.php file? If so Laragon normally detects it. Im not sure **.app** can be used as a local tld. Try changing the Hostname template to **{name}.test**

an alternative method would be to rename the app's folder from `workopia` to `workopia.app` and via Laragon Magic, you would end up with

`127.0.0.1      workopia.app.test            #laragon magic!`

the above method would also allow you to use 
`workopia.api.test` or `workopia.site.test` (for example) as the folders where you flesh out your API documentation and promotional site projects

**Comment by lambo-developer** [comment]
> my apologies @lambo-developer as a matter of course, I use `{Laragon Root}` as a placeholder for _your_ Laragon install location
> 
> not everyone's Laragon install is located on `C:\` drive, as can be seen from the image from @Pen-y-Fan above :) my intent was for you to replace the placholder with the correct Laragon root directory
> 
Oh I apologize, I updated it here;
```
define SITE "workopia"
define ROOT "C:/laragon/www/${SITE}/public"

<VirtualHost *:80>
    DocumentRoot "${ROOT}"
    ServerName ${SITE}
    ServerAlias *.${SITE}
    <Directory "${ROOT}">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

The issues I listed above still persist, on both URL's (workopia.test and localhost/workopia)

**Comment by kstingel** [comment]
@lambo-developer, could you send fresh screenshots showing the address bar as well as the response page please?
... and a shot from Explorer of your `www` folder?

I'll see if I can reproduce the errors

**Comment by kstingel** [comment]
something similar to _this_ is what we would expect to see
![image](https://github.com/leokhoa/laragon/assets/2832696/f22ad6fc-57bc-44e2-b1a0-56df7643ea41)

**Comment by lambo-developer** [comment]
> @lambo-developer, do you have a virtual host entry for port 443?
> 
> ```shell
> <VirtualHost *:443>
>     DocumentRoot "${ROOT}"
>     ServerName ${SITE}
>     ServerAlias *.${SITE}
>     <Directory "${ROOT}">
>         AllowOverride All
>         Require all granted
>     </Directory>
> </VirtualHost>
> ```

Added port 443;
```
<VirtualHost *:443>
```

Here is what I see when I navigate to "http://workopia.test";
https://prnt.sc/9uqmvB_neNTZ

Here is what I see when I navigate to "localhost/workopia"
https://prnt.sc/6QTlDFwCLMYP

Here is a screenshot from my Laragon www folder;
https://prnt.sc/jXqSyF9Gl1TJ

**Comment by kstingel** [comment]
first: Ctrl+click the info link on `worktopia.test` - it will open in a new tab
we're looking for the value of `$_SERVER['SCRIPT_FILENAME']`

try copying `index.php` from `C:/laragon/www` into `C:/laragon/www/worktopia/public`
it looks like `"http://workopia.test/"` may be pulling `index.php` from localhost because there is no index.php available in DocumentRoot

let me know if the resulting page shows the correct value for `Document Root:`

**Comment by lambo-developer** [comment]
> try copying `index.php` from `C:/laragon/www` into `C:/laragon/www/worktopia/public` it looks like `"http://workopia.test/"` may be pulling `index.php` from localhost because there is no index.php available in DocumentRoot
> 

I have a index.php in my document root (/public) but not in the workopia root;
https://prnt.sc/4MgjJP6iX8SQ - workopia root
https://prnt.sc/IjdYuSsKJZct - /public or document root

**Comment by kstingel** [comment]
is the `index.php` under `/public` the SAME `index.php` localhost displays, or have you created a custom file?

if it's custom, could you (temporarily) rename it to `index0.php` and copy localhost's index page over?

I'm specifically looking for the Directory Root value - as displayed by default `index.php`
as well as the value for **`$_SERVER['SCRIPT_FILENAME']`** when you open the `info` link from 
`/public/index.php`

because `workopia` exists under `www`, you may need to either put a `.htaccess` file in there redirecting to 
the `/public` folder, or (possibly) add an alias to the localhost config file (`00-default.conf`) 
to redirect `www/workopia` to `www/workopia/public` in order to prevent Apache listing dir 
contents if accessed via `localhost/workopia` - not 100% certain on that though.

**Comment by lambo-developer** [comment]
> is the `index.php` under `/public` the SAME `index.php` localhost displays, or have you created a custom file?
It is a custom file, the reason I don't have any index.php in the root dir of my project is because I made a custom MVC router, the /public index.php just loads views.

I copied over the localhost index.php into my folder and renamed the /public index.php to index0.php like you said to, now it displays a directory page;
https://prnt.sc/tzVtiwSNhiXn

When I click the workopia link;
https://prnt.sc/Pvcalb8IYauR

When I click the public link (points to the localhost index.php file I moved over);
https://prnt.sc/18YEsEzv5V09

When I click the info link;
https://prnt.sc/fOIXGZMDlbqs

About the last part I'm a little confused, would I put my .htaccess file in C:/Laragon or C:/Laragon/www

Here is my current .htaccess file;
```
Options -Indexes

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php [NC,L,QSA]
```

**Comment by kstingel** [comment]
(lines numbered for reference) current tree should look like: 
```shell
1 C:/Laragon
2 C:/Laragon/www # localhost
3 C:/Laragon/www/index.php # localhost/index.php
4 C:/Laragon/www/workopia/ # should not be browsable
5 C:/Laragon/www/workopia/public # workopia.test
6 # do you have a second workopia folder in here?
7 C:/Laragon/www/workopia/public/index.php # workopia.test/index.php
8 C:/Laragon/www/workopia/public/workopia/ # causing a directory loop effect
```

redirect from `localhost/workopia` would go into line 2
an alias is possbly safest way - you don't want people to be able to see (or download) your application's core code
something along the lines of `alias workopia -> workopia.test`
or possibly a `redirect permanent workopia -> workopia.test`

**Comment by lambo-developer** [comment]
Weirdly enough I got the issue fixed by re-installing Laragon and adding a Alias like you said. Thanks for all the help @kstingel

**Comment by Dkeane90** [comment]
I have followed this thread to a t and sadly it doesn't help. My issue is that my homepage now goes blank the minute I set my routes and my htaccess file.

**Comment by sucofog** [comment]
Is this for real, that you need to do huge steps just to make sites-enabled work?

LMAO.
