### ISSUE TITLE
Quick

### ISSUE THREAD

**Issue by diaolingzc** [leokhoa/laragon#70]
[Window Title]
Warning

[Content]
No file: D:\Development\laragon\tmp\downloads\wait-20190226201744.nodejs.node-v10.13.0-win-x64.zip

[OK]

**Comment by leokhoa** [comment]
@diaolingzc : Please update to Laragon 4.0.12?
https://forum.laragon.org/topic/1232/tutorial-how-to-upgrade-to-laragon-4-x-from-former-versions-laragon-3-x/2
