### ISSUE TITLE
Latest Apache with SSL Enabled: openssl Entry Point Not Found

### ISSUE THREAD

**Issue by andrechris24** [leokhoa/laragon#705]
I'm using latest Apache (version 2.4.58) on Windows 10 22H2. When Laragon detected changes in project folder (With SSL enabled), this error message shown twice while running either Apache or nginx:
![image_2024-02-25_130925365](https://github.com/leokhoa/laragon/assets/81963853/90256180-0101-49e5-b8a1-e3e51b60fda8)
The error message above also appears when enabling SSL. As a result, newly detected projects show "**Your connection is not private**" when opened with **https**:
![image_2024-02-25_132119048](https://github.com/leokhoa/laragon/assets/81963853/6ca99f03-a8f8-43b0-b3fb-402877192cc9)
This issue also exist while using **Apache 2.4.57**, but by switching Apache to version 2.4.54 (Laragon bundled), it's working fine.

So, what causes the OpenSSL error message?

**Comment by andrechris24** [comment]
Update: Running OpenSSL via Terminal also throws same error message, which makes OpenSSL didn't output anything.

Terminal output (I use Laragon's Terminal):
```
E:\staticweb\nextjs-dashboard(main -> origin)
λ openssl rand -base64 32

E:\staticweb\nextjs-dashboard(main -> origin)
λ openssl

E:\staticweb\nextjs-dashboard(main -> origin)
λ
```

**Comment by andrechris24** [comment]
I've updated Apache to 2.4.59, it seems the issue was fixed on apache's side. Closing this for now.

**Comment by raoazwar** [comment]
i am using 2.4.63 but still getting the ssl issue.

**Comment by leokhoa** [comment]
@raoazwar : How about other Apache version, such as 2.4.62
Ref: https://github.com/leokhoa/laragon/issues/705#issuecomment-2105501569
