### ISSUE TITLE
How to enable pcntl extension in laragon

### ISSUE THREAD

**Issue by nameshafa** [leokhoa/laragon#708]
I just saw people saying that Laragon had alternatives for pcntl extension in windows, is that still exists for the latest version of Laragon? and how to enable it

_Originally posted by @berto309 in https://github.com/leokhoa/laragon/discussions/378_

**Comment by sohaibilyas** [comment]
pcntl is not available on windows https://github.com/leokhoa/laragon/discussions/378#discussioncomment-4809075

**Comment by berto309** [comment]
Yes. Unfortunately it's not available on windows. I use Laravel homestead if I want to use Laravel horizon.
