### ISSUE TITLE
nts php settings

### ISSUE THREAD

**Issue by w3suli** [leokhoa/laragon#75]
Php.ini generated by laragon:
cgi.fix_pathinfo = 0

In some cases, this setting causes a "No input file specified" error.
Why does Laragon put this value to false?

The default would be:
cgi.fix_pathinfo = 1

**Comment by leokhoa** [comment]
@w3suli : It was a security best practice but I agree with you. Just let the value `cgi.fix_pathinfo = 1` by default.

**Comment by leokhoa** [comment]
@w3suli : I fixed it in Laragon 4.0.12
