### ISSUE TITLE
It's a nice app, but ;

### ISSUE THREAD

**Issue by bentorukmakto** [leokhoa/laragon#777]
Hello,

In order to use this beautiful application, I installed Windows on my Macbook and continued to work this way for about 1 year. But due to the unnecessary pressures of Windows, I couldn't stand it for long and went back to Macbook. I hope you will release a version for apple devices soon.

**Comment by benjivm** [comment]
Use Herd https://herd.laravel.com/ and DBngin https://dbngin.com/ instead.

**Comment by alxndr-w** [comment]
close?
