### ISSUE TITLE
How to configure this setting of disable Node.js 

### ISSUE THREAD

**Issue by yemaozi999** [leokhoa/laragon#791]
I don't want to use the built-in Node.js provided by Laragon, as it's causing issues with my environment. Could you guide me on where to configure this setting?

**Comment by leokhoa** [comment]
@yemaozi999 What is the issues? Node.js bundle is just a runtime.

**Comment by yemaozi999** [comment]
When I start Laragon, the program modifies my Node.js environment variables. As I frequently need to switch between different Node.js versions during development, this results in a disorganized environment setup. Therefore, I wish to disable the feature that automatically alters the environment variables upon startup.

**Comment by leokhoa** [comment]
@yemaozi999 : You can add and switch Node.js easily with Laragon.
For your case, just remove the nodejs folder in {laragon_path}/bin is enough.

**Comment by yemaozi999** [comment]
Alright, I understand now. I will give it a try and see if it still affects the environment variables. Thanks.
