### ISSUE TITLE
BrowserSync Package Options Proxy + Virtual Host doesn't LiveReload

### ISSUE THREAD

**Issue by Mil00Z** [leokhoa/laragon#8]
Since i use Laragon (before, use simple php internal server to launch my local project), i can't use the excellent Package "BrowserSync" to work easily 

[https://www.browsersync.io/docs/options/#option-proxy](url)

=> is able to proxy an url or a localhost configuration to get an LiveReload (css in my case).

I have no problem on real server of developpement with this options.

I like Laragon because is simple and fast, but browserSync is a kind of must have package to dev-front.

do you have any idea ?

**Comment by coderars** [comment]
@Mil00Z I think it's not a Laragon issue. For me browserSync works like a charm on my Laravel projects served by Laragon. If you are not familiar with Laravel framework, you could test it with Laragon to see how it implements `browserSync` with `npm `and `webpack`:

1. Try to create a Laravel test project in Laragon: `Quick create / Laravel` and name it "laravel"
2. If all went ok, `http://laravel.test` should work in your browser
3. Open a terminal in `www\laravel`  and run `npm install`
4. When finished, open `webpack.mix.js` file in your editor and add this line to its end:
```
mix.browserSync('laravel.test');
```
5. Back to the terminal and run `npm run watch` (run this command again when it finished installing dependencies)
6. `http://localhost:3000` should open in browser, but you can use it with `http://laravel.test:3000` either
7. Try to edit some text in `resources\views\welcome.blade.php` to see if reloading works
8. Look at the file `package.json` to see how it's all done

**Comment by betapixel** [comment]
Excelente respuesta.
Muchas gracias.
