### ISSUE TITLE
Notepadd++

### ISSUE THREAD

**Issue by Synthese** [leokhoa/laragon#84]
Is there an update for the Notepad Editor? Currently notepad ++ 7.6.4
I have to get rid of yours too
doing a great job here.

**Comment by w3suli** [comment]
Until it is updated. Just download the portable version:
https://notepad-plus-plus.org/repository/7.x/7.6.4/npp.7.6.4.bin.x64.zip
Unpack it in the "laragon\bin\notepad++" folder and ready.

**Comment by Synthese** [comment]
@w3suli Thanks for that, will load it immediately.
