### ISSUE TITLE
Dark theme, when selected

### ISSUE THREAD

**Issue by CoenCouwenberg** [leokhoa/laragon#86]
I just started using Laragon, and I like dark themes because it looks calmer to my eyes. But when I turn on the dark theme, selected areas text colors stays white 

[Link to image on the wrong form](https://softwarerecs.stackexchange.com/questions/57285/laragon-dark-theme-when-selected)

Now I can´t read the text written in the selected area anymore...

Does anyone know how I could fix this? Maybe just a stup*d question, it may be a carelessness mistake of them.

I would appreciate your reaction

**Comment by w3suli** [comment]
I think you addressed the request to the wrong place.
The bug is in HeidiSQL. This is used by Laragon for database management.

[https://github.com/HeidiSQL/HeidiSQL](https://github.com/HeidiSQL/HeidiSQL)
