### ISSUE TITLE
Apache can't start

### ISSUE THREAD

**Issue by ziselive** [leokhoa/laragon#87]
![Alt Text](http://m.qpic.cn/psb?/V141E7tu37pl5g/8e66iZg9BGSnYLBkSWzIFubPaBJM.EmPYdpR9HQN3GQ!/b/dFQBAAAAAAAA&bo=4QEdAQAAAAADF84!&rf=viewer_4&t=5)

The apache httpd-2.4.38-win64-VC15 version cannot be started.
The runtime libraries are all installed.
Only version 2.4.38 cannot be started. 2.4.35 is normal.

win7 X64

I have tried to reinstall visual C++ redistributable and all versions of 2008-2019 are installed. Visual studio 2017 is also installed. But still can't start.

Installing apache2.4.38 directly in the computer system can run normally.

**Comment by ziselive** [comment]
The apache high version will show this error. The lower version works fine.

**Comment by ziselive** [comment]
This problem has been resolved, the low version of the PHP SSL library causes Apache to fail to start.

**Comment by abrhambas01** [comment]
@ziselive , how did you do it bro ?

**Comment by ziselive** [comment]
@abrhambas01  hi，Need to install the latest apache and PHP. Or php install the latest version. Then start again.

Because apache will copy the php library at startup.
