### ISSUE TITLE
App freeze

### ISSUE THREAD

**Issue by boberski666** [leokhoa/laragon#876]
When I lunch apache and sql and than close them app freeze and a need to use task manager to kill app.

**Comment by alxndr-w** [comment]
duplicate #836

**Comment by boberski666** [comment]
and?

**Comment by alxndr-w** [comment]
and so you can close this one.

**Comment by boberski666** [comment]
What is the solution?

**Comment by alxndr-w** [comment]
In GitHub, it's common to close duplicate tickets and to discuss in the original one #836

**Comment by boberski666** [comment]
It is not the same, but ok...

and...

Nie ucz mnie debilu na temat kultury...

**Comment by alxndr-w** [comment]
Miłego dnia, sąsiadko. 🫰🏻
