### ISSUE TITLE
Is there an ability to add multiple ending url paths using laragon?

### ISSUE THREAD

**Issue by torressam333** [leokhoa/laragon#92]
I do like how easy it is to configure the auto virtual hosts. My issue is, if I set the ending path for Auto VH's to lets say... example.test, is there a way to run two separate domain names with different ending URL paths? So could I run to named URL's at the same time:

//Diff URL's
URL 1: example.test
URL 2: testsite.dev.io

Is there a way to change settings in Laragon to recognize multiple ending url paths? Or even two completely different URL paths?

**Comment by leokhoa** [comment]
@torressam333 : 
```
If you have a specific project which has modified content, just remove the auto. prefix, Laragon will keep the content of the .conf file intact.
```
Ref: https://laragon.org/docs/pretty-urls.html

In your case, just add `testsite.dev.io` to the the correspond virtual host and remember to remove the "auto." prefix of the file.

**Comment by torressam333** [comment]
So, I created a .conf file named testsite.dev.io, and I made sure that the auto prefix was removed.

This is what I have in my testsite.dev.io conf file:

<VirtualHost *:80> 
    DocumentRoot "C:/laragon/www/testsite/public/"
    ServerName testsite.dev.io
    ServerAlias *.testsite.dev.io
    <Directory "C:/laragon/www/testsite/public/">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# If you want to use SSL, enable it by going to Menu > Apache > SSL > Enabled


I restarted Laragon Apache and Mysql, when I type in: testsite.dev.io/ .... I get redirected back my ISP's site telling me that the url does not exist.

Do I have an error in my conf file? Or what could I be doing wrong?

Thank you for the help!

**Comment by leokhoa** [comment]
@torressam333 : You need to update the hosts file also.
Open hosts file (the `h` letter on the top right of Laragon UI), then type:
```
127.0.0.1                testsite.dev.io
```

**Comment by torressam333** [comment]
You are awesome @leokhoa

Thank you!!! Laragon is the best.

**Comment by suheth** [comment]
Thank You!
