### ISSUE TITLE
[v7.0.0] Empty entry in Quick add (packages.conf)

### ISSUE THREAD

**Issue by husnilkhatimi** [leokhoa/laragon#943]
This line in packages.conf creates an empty entry, will attempt to download and output "No file" error when clicked.

![laragon700_bug_packages_empty_line](https://github.com/user-attachments/assets/a5fc9001-8f33-44ab-ade1-e720328ecfd7)

I think its parameters for VS code setup right?

**Comment by leokhoa** [comment]
@husnilkhatimi : This packages.conf is old. I fixed that in Laragon 7.0.1 setup. It can be found in the Announcement: https://github.com/leokhoa/laragon/releases/tag/7.0.0

**Comment by husnilkhatimi** [comment]
Noted. I will update manually first. Thanks
