### ISSUE TITLE
另一款好用的专业的集成开发环境，phpenv.cn

### ISSUE THREAD

**Issue by xianyun666** [leokhoa/laragon#97]
大家好，我是phpenv的开发者，官网：https://www.phpenv.cn
关于它的详情和优点可以看介绍：
https://www.phpenv.cn/trait.html

**Comment by leokhoa** [comment]
@xianyun666 : Is it ethic when you advertise your software on the issue page of Laragon?

**Comment by xianyun666** [comment]
分享一直是GitHub这个平台的精神，而我因为热爱php才自己动手写了一款phpEnv，并且它是免费的，专业的，优雅的，强大的。欢迎你对他试用和提出意见。
peace and love
