### ISSUE TITLE
Quick add packages slow download

### ISSUE THREAD

**Issue by yanottamao** [leokhoa/laragon#98]
Slow download from github in-app quick add packages feature. Around 20kBps on 20mbps internet speed.

**Comment by yanottamao** [comment]
Slow download from github in-app quick add packages feature. Around 20kBps on 20mbps internet speed.

**Comment by leokhoa** [comment]
@yanottamao : Does it happen consistently?

**Comment by yanottamao** [comment]
@leokhoa no, it's just occasionally. But I never get above 300 kBps inside quick add. And looks like it's only in some packages like devkit, so not all packages affected by slow download.

**Comment by fangke2688** [comment]
You can download it in advance by configuration, then set up a web server locally or put it on a server on the Internet, and download it by modifying the download address in the configuration. --- Google Translate

**Comment by yanottamao** [comment]
@fangke2688 could I just download the file manually and edit the configuration to point to local files?

**Comment by leokhoa** [comment]
@yanottamao : Yes, you can.

**Comment by yanottamao** [comment]
@leokhoa ah, I see. Thank you for your support Leo. I'll just download and point it locally then.

**Comment by leokhoa** [comment]
@yanottamao : You're welcome :)
